openapi: 3.0.3
info:
  title: API de Gestión de Árboles - Categorías e-commerce
  version: 1.0.0
  description: API completa para el manejo de estructuras jerárquicas (Proyecto Universidad Mariano Gálvez).

paths:
  # 1. Crear nodo raíz
  /nodes/root:
    post:
      summary: Crear el nodo raíz
      tags:
        - Árbol
      responses:
        '201':
          description: Raíz creada exitosamente

  # 2. Agregar hijos
  /nodes/{parentId}/children:
    post:
      summary: Agregar un hijo a un nodo existente
      tags:
        - Árbol
      parameters:
        - name: parentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Nodo hijo agregado correctamente

  # 3. Obtener el árbol completo
  /tree:
    get:
      summary: Obtener la estructura completa del árbol
      tags:
        - Árbol
      responses:
        '200':
          description: Estructura completa retornada con éxito

  # 4. Recorridos (DFS y BFS) - Operaciones 6 y 7
  /tree/traversal:
    get:
      summary: Obtener recorrido del árbol
      tags:
        - Algoritmos
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum: [DFS, BFS]
      responses:
        '200':
          description: Lista de nodos en el orden solicitado

  # 5. Métricas del nodo  - Operaciones 8, 9 y 10
  /nodes/{nodeId}/info:
    get:
      summary: Obtener métricas y ancestros de un nodo específico
      tags:
        - Métricas
      parameters:
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retorna altura, profundidad y lista de ancestros

  # 6. Gestión de Subárboles - Operaciones 4 y 5
  /nodes/{nodeId}/subtree:
    get:
      summary: Obtener el subárbol o el camino desde la raíz
      tags:
        - Estructura
      parameters:
        - name: nodeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Retorna el subárbol que parte desde este nodo

  # 7. Validación de Ciclos - Operación 11
  /tree/validate:
    get:
      summary: Validar que la estructura no tenga ciclos
      tags:
        - Validación
      responses:
        '200':
          description: Resultado de la validación (True/False)