app.storage=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/arbol_db
spring.datasource.username=postgres
spring.datasource.password=Flores05
spring.datasource.driver-class-name=org.postgresql.Driver