app.storage=memory

spring.datasource.url=jdbc:postgresql://localhost:5432/arbol_db
spring.datasource.username=postgres
spring.datasource.password=Gabriel13
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql