spring.profiles.active=postgres

app.storage=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/arbol_db
spring.datasource.username=postgres
spring.datasource.password=asdfg
spring.datasource.driver-class-name=org.postgresql.Driver